"""Public exports for the Veto Python SDK.

The base wheel intentionally keeps import-time dependencies to the Python
standard library. Optional cloud, admin, YAML, proxy, and integration surfaces
are loaded only when their exported names are accessed.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any


_EXPORTS: dict[str, tuple[str, str]] = {
    "Veto": ("veto.core.veto", "Veto"),
    "ToolCallDeniedError": ("veto.core.veto", "ToolCallDeniedError"),
    "GuardResult": ("veto.core.veto", "GuardResult"),
    "VetoOptions": ("veto.core.veto", "VetoOptions"),
    "VetoMode": ("veto.core.veto", "VetoMode"),
    "ValidationMode": ("veto.core.veto", "ValidationMode"),
    "WrappedTools": ("veto.core.veto", "WrappedTools"),
    "WrappedMCPTools": ("veto.core.veto", "WrappedMCPTools"),
    "WrappedHandler": ("veto.core.veto", "WrappedHandler"),
    "protect": ("veto.core.protect", "protect"),
    "DecisionOutcome": ("veto.receipts", "DecisionOutcome"),
    "DecisionReceiptPayload": ("veto.receipts", "DecisionReceiptPayload"),
    "ReceiptSummary": ("veto.receipts", "ReceiptSummary"),
    "append_receipt": ("veto.receipts", "append_receipt"),
    "build_decision_receipt": ("veto.receipts", "build_decision_receipt"),
    "format_ndjson": ("veto.receipts", "format_ndjson"),
    "hash_receipt": ("veto.receipts", "hash_receipt"),
    "parse_ndjson": ("veto.receipts", "parse_ndjson"),
    "receipt_summary": ("veto.receipts", "receipt_summary"),
    "validate_receipt_payload": ("veto.receipts", "validate_receipt_payload"),
    "verify_file": ("veto.receipts", "verify_file"),
    "verify_receipt_chain": ("veto.receipts", "verify_receipt_chain"),
    "ApiKeyInfo": ("veto.admin", "ApiKeyInfo"),
    "ApiKeyCreated": ("veto.admin", "ApiKeyCreated"),
    "AdminApproval": ("veto.admin", "Approval"),
    "BatchResolveApprovalItem": ("veto.admin", "BatchResolveApprovalItem"),
    "BatchResolveApprovalResult": ("veto.admin", "BatchResolveApprovalResult"),
    "BatchResolveApprovalsResponse": ("veto.admin", "BatchResolveApprovalsResponse"),
    "Constraint": ("veto.admin", "Constraint"),
    "CreatePolicyDraftInput": ("veto.admin", "CreatePolicyDraftInput"),
    "CreatePolicyInput": ("veto.admin", "CreatePolicyInput"),
    "CreateUpstreamInput": ("veto.admin", "CreateUpstreamInput"),
    "AdminDecision": ("veto.admin", "Decision"),
    "DecisionQuery": ("veto.admin", "DecisionQuery"),
    "DecisionStats": ("veto.admin", "DecisionStats"),
    "EventSubscription": ("veto.admin", "EventSubscription"),
    "LlmConfig": ("veto.admin", "LlmConfig"),
    "McpUpstream": ("veto.admin", "McpUpstream"),
    "Organization": ("veto.admin", "Organization"),
    "AdminOutputRule": ("veto.admin", "OutputRule"),
    "PaginatedResult": ("veto.admin", "PaginatedResult"),
    "Policy": ("veto.admin", "Policy"),
    "PolicyDraft": ("veto.admin", "PolicyDraft"),
    "Project": ("veto.admin", "Project"),
    "ProjectCreated": ("veto.admin", "ProjectCreated"),
    "AdminSessionConstraints": ("veto.admin", "SessionConstraints"),
    "AdminTool": ("veto.admin", "Tool"),
    "UpdatePolicyInput": ("veto.admin", "UpdatePolicyInput"),
    "UpstreamTestResult": ("veto.admin", "UpstreamTestResult"),
    "VetoAdmin": ("veto.admin", "VetoAdmin"),
    "VetoAdminError": ("veto.admin", "VetoAdminError"),
    "VetoAdminEvent": ("veto.admin", "VetoAdminEvent"),
    "VetoAdminOptions": ("veto.admin", "VetoAdminOptions"),
    "ToolDefinition": ("veto.types.tool", "ToolDefinition"),
    "ToolCall": ("veto.types.tool", "ToolCall"),
    "ToolResult": ("veto.types.tool", "ToolResult"),
    "ToolHandler": ("veto.types.tool", "ToolHandler"),
    "ExecutableTool": ("veto.types.tool", "ExecutableTool"),
    "ToolInputSchema": ("veto.types.tool", "ToolInputSchema"),
    "JsonSchemaType": ("veto.types.tool", "JsonSchemaType"),
    "JsonSchemaProperty": ("veto.types.tool", "JsonSchemaProperty"),
    "DecisionExportFormat": ("veto.types.config", "DecisionExportFormat"),
    "DecisionExportRecord": ("veto.types.config", "DecisionExportRecord"),
    "LogLevel": ("veto.types.config", "LogLevel"),
    "StreamLogMode": ("veto.types.config", "StreamLogMode"),
    "ValidationDecision": ("veto.types.config", "ValidationDecision"),
    "ValidationResult": ("veto.types.config", "ValidationResult"),
    "ValidationContext": ("veto.types.config", "ValidationContext"),
    "Validator": ("veto.types.config", "Validator"),
    "NamedValidator": ("veto.types.config", "NamedValidator"),
    "ToolCallHistoryEntry": ("veto.types.config", "ToolCallHistoryEntry"),
    "ToolRegistration": ("veto.cloud.types", "ToolRegistration"),
    "ToolParameter": ("veto.cloud.types", "ToolParameter"),
    "ValidationRequest": ("veto.cloud.types", "ValidationRequest"),
    "ValidationResponse": ("veto.cloud.types", "ValidationResponse"),
    "FailedConstraint": ("veto.cloud.types", "FailedConstraint"),
    "ApprovalData": ("veto.cloud.types", "ApprovalData"),
    "ApprovalPollOptions": ("veto.cloud.types", "ApprovalPollOptions"),
    "RuntimeActionCreateRequest": ("veto.cloud.types", "RuntimeActionCreateRequest"),
    "RuntimeActionData": ("veto.cloud.types", "RuntimeActionData"),
    "VetoCloudClient": ("veto.cloud.client", "VetoCloudClient"),
    "VetoCloudConfig": ("veto.cloud.client", "VetoCloudConfig"),
    "ApprovalTimeoutError": ("veto.cloud.client", "ApprovalTimeoutError"),
    "RuntimeActionTimeoutError": ("veto.cloud.client", "RuntimeActionTimeoutError"),
    "PolicyCache": ("veto.cloud.policy_cache", "PolicyCache"),
    "ArgumentConstraint": ("veto.deterministic.types", "ArgumentConstraint"),
    "DeterministicPolicy": ("veto.deterministic.types", "DeterministicPolicy"),
    "LocalValidationResult": ("veto.deterministic.types", "LocalValidationResult"),
    "ConstraintCheckResult": ("veto.deterministic.types", "ConstraintCheckResult"),
    "ValidationEntry": ("veto.deterministic.types", "ValidationEntry"),
    "validate_deterministic": ("veto.deterministic.validator", "validate_deterministic"),
    "is_safe_pattern": ("veto.deterministic.regex_safety", "is_safe_pattern"),
    "AP2Connector": ("veto.economic", "AP2Connector"),
    "BudgetCheckResult": ("veto.economic", "BudgetCheckResult"),
    "BudgetEngine": ("veto.economic", "BudgetEngine"),
    "BudgetScope": ("veto.economic", "BudgetScope"),
    "EconomicBudgetConfig": ("veto.economic", "EconomicBudgetConfig"),
    "EconomicBudgetStatus": ("veto.economic", "EconomicBudgetStatus"),
    "EconomicContext": ("veto.economic", "EconomicContext"),
    "EconomicDenialDetails": ("veto.economic", "EconomicDenialDetails"),
    "EconomicDenialReason": ("veto.economic", "EconomicDenialReason"),
    "EconomicEvaluationResult": ("veto.economic", "EconomicEvaluationResult"),
    "EconomicEvaluator": ("veto.economic", "EconomicEvaluator"),
    "EconomicProtocol": ("veto.economic", "EconomicProtocol"),
    "LocalBudgetEngine": ("veto.economic", "LocalBudgetEngine"),
    "MPPConnector": ("veto.economic", "MPPConnector"),
    "ProtocolConnector": ("veto.economic", "ProtocolConnector"),
    "X402Connector": ("veto.economic", "X402Connector"),
    "buildAP2ConnectorError": ("veto.economic", "buildAP2ConnectorError"),
    "buildMPPConnectorError": ("veto.economic", "buildMPPConnectorError"),
    "buildX402ConnectorError": ("veto.economic", "buildX402ConnectorError"),
    "build_ap2_connector_error": ("veto.economic", "build_ap2_connector_error"),
    "build_mpp_connector_error": ("veto.economic", "build_mpp_connector_error"),
    "build_x402_connector_error": ("veto.economic", "build_x402_connector_error"),
    "createAP2Connector": ("veto.economic", "createAP2Connector"),
    "createMPPConnector": ("veto.economic", "createMPPConnector"),
    "createX402Connector": ("veto.economic", "createX402Connector"),
    "create_ap2_connector": ("veto.economic", "create_ap2_connector"),
    "create_mpp_connector": ("veto.economic", "create_mpp_connector"),
    "create_x402_connector": ("veto.economic", "create_x402_connector"),
    "parse_economic_budget_configs": ("veto.economic", "parse_economic_budget_configs"),
    "ExtractedEntities": ("veto.extractors", "ExtractedEntities"),
    "ExtractEntitiesOptions": ("veto.extractors", "ExtractEntitiesOptions"),
    "extractEntities": ("veto.extractors", "extractEntities"),
    "extract_entities": ("veto.extractors", "extract_entities"),
    "KernelClient": ("veto.kernel", "KernelClient"),
    "KernelConfig": ("veto.kernel", "KernelConfig"),
    "KernelError": ("veto.kernel", "KernelError"),
    "KernelParseError": ("veto.kernel", "KernelParseError"),
    "KernelResponse": ("veto.kernel", "KernelResponse"),
    "KernelToolCall": ("veto.kernel", "KernelToolCall"),
    "buildPrompt": ("veto.kernel", "buildPrompt"),
    "buildSystemPrompt": ("veto.kernel", "buildSystemPrompt"),
    "build_prompt": ("veto.kernel", "build_prompt"),
    "build_system_prompt": ("veto.kernel", "build_system_prompt"),
    "createKernelClient": ("veto.kernel", "createKernelClient"),
    "create_kernel_client": ("veto.kernel", "create_kernel_client"),
    "formatRules": ("veto.kernel", "formatRules"),
    "formatToolCall": ("veto.kernel", "formatToolCall"),
    "format_rules": ("veto.kernel", "format_rules"),
    "format_tool_call": ("veto.kernel", "format_tool_call"),
    "parse_kernel_response": ("veto.kernel", "parse_kernel_response"),
    "resolve_kernel_config": ("veto.kernel", "resolve_kernel_config"),
    "CustomAPIKeyError": ("veto.custom", "CustomAPIKeyError"),
    "CustomClient": ("veto.custom", "CustomClient"),
    "CustomConfig": ("veto.custom", "CustomConfig"),
    "CustomConfigError": ("veto.custom", "CustomConfigError"),
    "CustomError": ("veto.custom", "CustomError"),
    "CustomParseError": ("veto.custom", "CustomParseError"),
    "CustomProvider": ("veto.custom", "CustomProvider"),
    "CustomResponse": ("veto.custom", "CustomResponse"),
    "CustomToolCall": ("veto.custom", "CustomToolCall"),
    "buildProviderMessages": ("veto.custom", "buildProviderMessages"),
    "buildUserPrompt": ("veto.custom", "buildUserPrompt"),
    "build_provider_messages": ("veto.custom", "build_provider_messages"),
    "build_user_prompt": ("veto.custom", "build_user_prompt"),
    "createCustomClient": ("veto.custom", "createCustomClient"),
    "create_custom_client": ("veto.custom", "create_custom_client"),
    "resolve_custom_config": ("veto.custom", "resolve_custom_config"),
    "InterceptionResult": ("veto.core.interceptor", "InterceptionResult"),
    "HistoryStats": ("veto.core.history", "HistoryStats"),
    "OutputValidationResult": ("veto.core.output_validator", "OutputValidationResult"),
    "EventWebhookConfig": ("veto.core.events", "EventWebhookConfig"),
    "WebhookEvent": ("veto.core.events", "WebhookEvent"),
    "WebhookEventType": ("veto.core.events", "WebhookEventType"),
    "WebhookFormat": ("veto.core.events", "WebhookFormat"),
    "format_slack_payload": ("veto.core.events", "format_slack_payload"),
    "format_pagerduty_payload": ("veto.core.events", "format_pagerduty_payload"),
    "format_generic_payload": ("veto.core.events", "format_generic_payload"),
    "format_cef_payload": ("veto.core.events", "format_cef_payload"),
    "validate_policy_ir": ("veto.rules.schema_validator", "validate_policy_ir"),
    "PolicySchemaError": ("veto.rules.schema_validator", "PolicySchemaError"),
    "PolicyValidationError": ("veto.rules.schema_validator", "PolicyValidationError"),
    "OUTPUT_PATTERNS": ("veto.rules.patterns", "OUTPUT_PATTERNS"),
    "OUTPUT_PATTERN_SSN": ("veto.rules.patterns", "OUTPUT_PATTERN_SSN"),
    "OUTPUT_PATTERN_CREDIT_CARD": ("veto.rules.patterns", "OUTPUT_PATTERN_CREDIT_CARD"),
    "OUTPUT_PATTERN_OPENAI_API_KEY": ("veto.rules.patterns", "OUTPUT_PATTERN_OPENAI_API_KEY"),
    "OUTPUT_PATTERN_GITHUB_API_KEY": ("veto.rules.patterns", "OUTPUT_PATTERN_GITHUB_API_KEY"),
    "OUTPUT_PATTERN_AWS_API_KEY": ("veto.rules.patterns", "OUTPUT_PATTERN_AWS_API_KEY"),
    "OUTPUT_PATTERN_EMAIL": ("veto.rules.patterns", "OUTPUT_PATTERN_EMAIL"),
    "OUTPUT_PATTERN_US_PHONE": ("veto.rules.patterns", "OUTPUT_PATTERN_US_PHONE"),
    "FeedFallback": ("veto.rules.feed_provider", "FeedFallback"),
    "FeedProvider": ("veto.rules.feed_provider", "FeedProvider"),
    "FeedSnapshot": ("veto.rules.feed_provider", "FeedSnapshot"),
    "InMemoryFeedProvider": ("veto.rules.feed_provider", "InMemoryFeedProvider"),
    "is_condition_value_ref": ("veto.rules.feed_provider", "is_condition_value_ref"),
    "resolve_feed_ref": ("veto.rules.feed_provider", "resolve_feed_ref"),
    "LocalEvalOptions": ("veto.rules.local_evaluator", "LocalEvalOptions"),
    "LocalEvalResult": ("veto.rules.local_evaluator", "LocalEvalResult"),
    "evaluate_rules_locally": ("veto.rules.local_evaluator", "evaluate_rules_locally"),
    "PipelineBudget": ("veto.rules.pipeline_dsl", "PipelineBudget"),
    "PipelineOutput": ("veto.rules.pipeline_dsl", "PipelineOutput"),
    "PipelineSchedule": ("veto.rules.pipeline_dsl", "PipelineSchedule"),
    "PipelineSpec": ("veto.rules.pipeline_dsl", "PipelineSpec"),
    "PipelineStep": ("veto.rules.pipeline_dsl", "PipelineStep"),
    "canonicalize_json": ("veto.rules.pipeline_dsl", "canonicalize_json"),
    "compute_pipeline_id": ("veto.rules.pipeline_dsl", "compute_pipeline_id"),
    "parse_pipeline_spec": ("veto.rules.pipeline_dsl", "parse_pipeline_spec"),
    "stamp_pipeline_id": ("veto.rules.pipeline_dsl", "stamp_pipeline_id"),
    "verify_pipeline_id": ("veto.rules.pipeline_dsl", "verify_pipeline_id"),
    "to_openai": ("veto.providers.adapters", "to_openai"),
    "from_openai": ("veto.providers.adapters", "from_openai"),
    "from_openai_tool_call": ("veto.providers.adapters", "from_openai_tool_call"),
    "to_openai_tools": ("veto.providers.adapters", "to_openai_tools"),
    "to_anthropic": ("veto.providers.adapters", "to_anthropic"),
    "from_anthropic": ("veto.providers.adapters", "from_anthropic"),
    "from_anthropic_tool_use": ("veto.providers.adapters", "from_anthropic_tool_use"),
    "to_anthropic_tools": ("veto.providers.adapters", "to_anthropic_tools"),
    "to_google_tool": ("veto.providers.adapters", "to_google_tool"),
    "from_google_function_call": ("veto.providers.adapters", "from_google_function_call"),
    "to_mcp": ("veto.providers.adapters", "to_mcp"),
    "from_mcp": ("veto.providers.adapters", "from_mcp"),
    "from_mcp_tool_call": ("veto.providers.adapters", "from_mcp_tool_call"),
    "to_mcp_tools": ("veto.providers.adapters", "to_mcp_tools"),
    "is_mcp_tool": ("veto.providers.adapters", "is_mcp_tool"),
    "extract_mcp_economic_context": ("veto.providers.adapters", "extract_mcp_economic_context"),
    "ProxyConfig": ("veto.proxy", "ProxyConfig"),
    "ProxyServer": ("veto.proxy", "ProxyServer"),
    "start_proxy_server": ("veto.proxy", "start_proxy_server"),
    "OpenAITool": ("veto.providers.types", "OpenAITool"),
    "OpenAIToolCall": ("veto.providers.types", "OpenAIToolCall"),
    "AnthropicTool": ("veto.providers.types", "AnthropicTool"),
    "AnthropicToolUse": ("veto.providers.types", "AnthropicToolUse"),
    "GoogleTool": ("veto.providers.types", "GoogleTool"),
    "GoogleFunctionCall": ("veto.providers.types", "GoogleFunctionCall"),
    "MCPInputSchema": ("veto.providers.types", "MCPInputSchema"),
    "MCPTool": ("veto.providers.types", "MCPTool"),
    "MCPToolCallArgs": ("veto.providers.types", "MCPToolCallArgs"),
    "MCPContentBlock": ("veto.providers.types", "MCPContentBlock"),
    "MCPToolResult": ("veto.providers.types", "MCPToolResult"),
    "MCPServerClient": ("veto.providers.types", "MCPServerClient"),
    "RateLimitEntry": ("veto.rate_limiting.types", "RateLimitEntry"),
    "check_and_record": ("veto.rate_limiting.store", "check_and_record"),
    "clear_store": ("veto.rate_limiting.store", "clear_store"),
    "evaluate_rate_limits": ("veto.rate_limiting.evaluator", "evaluate_rate_limits"),
    "RateLimitStore": ("veto.rate_limiting.evaluator", "RateLimitStore"),
    "compute_chain_hash": ("veto.audit.chain", "compute_chain_hash"),
    "GENESIS_HASH": ("veto.audit.chain", "GENESIS_HASH"),
    "try_load_otel": ("veto.observability.otel", "try_load_otel"),
    "VetoTracer": ("veto.observability.otel", "VetoTracer"),
    "VetoSpan": ("veto.observability.otel", "VetoSpan"),
    "SPAN_STATUS_OK": ("veto.observability.otel", "SPAN_STATUS_OK"),
    "SPAN_STATUS_ERROR": ("veto.observability.otel", "SPAN_STATUS_ERROR"),
    "run_tests": ("veto.testing.runner", "run_tests"),
    "VetoTestCase": ("veto.testing.types", "VetoTestCase"),
    "VetoTestSuite": ("veto.testing.types", "VetoTestSuite"),
    "VetoTestResult": ("veto.testing.types", "VetoTestResult"),
    "VetoTestRunResult": ("veto.testing.types", "VetoTestRunResult"),
}

__all__ = list(_EXPORTS)


def __getattr__(name: str) -> Any:
    try:
        module_name, export_name = _EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc

    module = import_module(module_name)
    value = getattr(module, export_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *__all__})
