{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.fqdn.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "veto.fullname" . }}-fqdn-egress
  labels:
    {{- include "veto.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  egress:
    - toFQDNs:
        {{- range .Values.networkPolicy.fqdn.allowedNames }}
        - matchName: {{ . | quote }}
        {{- end }}
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
{{- end }}
