apiVersion: v1
kind: Secret
metadata:
  name: {{ include "veto.fullname" . }}-license
  labels:
    {{- include "veto.labels" . | nindent 4 }}
type: Opaque
stringData:
  license: {{ required "Set .Values.license to your Veto BYOC license" .Values.license | quote }}
