apiVersion: v1
kind: Service
metadata:
  name: {{ include "veto.fullname" . }}-server
  labels:
    app.kubernetes.io/component: server
    {{- include "veto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.server.type }}
  ports:
    - name: http
      port: {{ .Values.service.server.port }}
      targetPort: 3001
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: {{ .Release.Name }}
